/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 modern_kitchen.glb 
Author: Visthétique (https://sketchfab.com/visthetique)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/modern-kitchen-82c35500aec347d2938ff7943900486f
Title: Modern Kitchen
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Kitchen(props) {
  const { nodes, materials } = useGLTF('/models/modern_kitchen.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.606}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[-481.272, 255.062, -333.974]} rotation={[0, Math.PI / 2, 0]} scale={4.472}>
            <mesh geometry={nodes.CLC855_URBAN_Black_0.geometry} material={materials.Black} />
            <mesh geometry={nodes.CLC855_URBAN_Bright_Metal_0.geometry} material={materials.Bright_Metal} />
            <mesh geometry={nodes.CLC855_URBAN_Night_River_Black_Front_0.geometry} material={materials.Night_River_Black_Front} />
            <mesh geometry={nodes.CLC855_URBAN_Night_River_Black_0.geometry} material={materials.Night_River_Black} />
            <mesh geometry={nodes.CLC855_URBAN_Grey_0.geometry} material={materials.Grey} />
          </group>
          <group position={[162.494, 237.549, -245.921]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cabinets_Closet_0.geometry} material={materials.Closet} />
            <mesh geometry={nodes.Cabinets_Chrome_0.geometry} material={materials.Chrome} />
            <mesh geometry={nodes.Cabinets_OakWood_0.geometry} material={materials.OakWood} />
            <mesh geometry={nodes.Cabinets_White_0.geometry} material={materials.White} />
            <mesh geometry={nodes.Cabinets_Countertop_0.geometry} material={materials.Countertop} />
          </group>
          <group position={[-96.064, 323.934, -544.387]} rotation={[-Math.PI / 2, 0, 0]} scale={[7.253, 14.425, 7.253]}>
            <mesh geometry={nodes.Component__Metal_Corrogated_Shiny_2_0.geometry} material={materials.Metal_Corrogated_Shiny_2} />
            <mesh geometry={nodes.Component_Chrome_0.geometry} material={materials.Chrome} />
            <mesh geometry={nodes.Component_Chrome_0_1.geometry} material={materials.Chrome} />
            <mesh geometry={nodes.Component_Chrome_0_2.geometry} material={materials.Chrome} />
            <mesh geometry={nodes.Component_Glass_0.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Component__Metal_Corrogated_Shiny_1_0.geometry} material={materials.Metal_Corrogated_Shiny_1} />
          </group>
          <group position={[401.576, 312.823, -370.254]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={75.84}>
            <mesh geometry={nodes.DDDD_cup1_2_0.geometry} material={materials.cup1_2} />
            <mesh geometry={nodes.DDDD_cup1_1_0.geometry} material={materials.cup1_1} />
            <mesh geometry={nodes.DDDD_cup5_1_0.geometry} material={materials.cup5_1} />
            <mesh geometry={nodes.DDDD_cup5_2_0.geometry} material={materials.cup5_2} />
            <mesh geometry={nodes.DDDD_cup4_1_0.geometry} material={materials.cup4_1} />
            <mesh geometry={nodes.DDDD_cup4_2_0.geometry} material={materials.cup4_2} />
            <mesh geometry={nodes.DDDD_cup6_2_0.geometry} material={materials.cup6_2} />
            <mesh geometry={nodes.DDDD_cup6_1_0.geometry} material={materials.cup6_1} />
          </group>
          <group position={[403.292, 237.177, -573.383]} rotation={[-Math.PI / 2, 0, 0]} scale={82.381}>
            <mesh geometry={nodes.DDDD001_Plywood_A_50cm_0.geometry} material={materials.Plywood_A_50cm} />
            <mesh geometry={nodes.DDDD001_Porcelain_A01_White_10cm_0.geometry} material={materials.Porcelain_A01_White_10cm} />
            <mesh geometry={nodes.DDDD001_Plywood_C_50cm_0.geometry} material={materials.Plywood_C_50cm} />
          </group>
          <group position={[64.417, 185.679, -207.373]} rotation={[-Math.PI / 2, 0, 0]} scale={51.567}>
            <mesh geometry={nodes.DDDD002_Plywood_C_50cm_0.geometry} material={materials.Plywood_C_50cm} />
            <mesh geometry={nodes.DDDD002_OakWood_0.geometry} material={materials.OakWood} />
            <mesh geometry={nodes.DDDD002_banana2_0.geometry} material={materials.banana2} />
          </group>
          <group position={[384.717, 381.106, 102.308]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.DDDD003_Glass_0.geometry} material={materials.Glass} />
            <mesh geometry={nodes.DDDD003_Glass_0_1.geometry} material={materials.Glass} />
            <mesh geometry={nodes.DDDD003_Glass_0_2.geometry} material={materials.Glass} />
          </group>
          <group position={[228.651, 378.453, -536.508]} rotation={[-Math.PI / 2, 0, 0]} scale={53.633}>
            <mesh geometry={nodes.DDDD004_Plywood_A_50cm_0.geometry} material={materials.Plywood_A_50cm} />
            <mesh geometry={nodes.DDDD004_wire_2_0.geometry} material={materials.wire_2} />
            <mesh geometry={nodes.DDDD004_Glass_0.geometry} material={materials.Glass} />
            <mesh geometry={nodes.DDDD004_Material__7_0.geometry} material={materials.Material__7} />
            <mesh geometry={nodes.DDDD004_wire_3_0.geometry} material={materials.Onyx} />
          </group>
          <group position={[-514.584, 27.961, -334.401]} rotation={[0, Math.PI / 2, 0]} scale={[6.602, 6.138, 6.138]}>
            <mesh geometry={nodes['DSI+46750_Black_0'].geometry} material={materials.Black} />
            <mesh geometry={nodes['DSI+46750_Material_0'].geometry} material={materials.Material} />
            <mesh geometry={nodes['DSI+46750_DSI_46750_Screen_0'].geometry} material={materials.DSI_46750_Screen} />
            <mesh geometry={nodes['DSI+46750_DSI_46750_Door_0'].geometry} material={materials.DSI_46750_Door} />
          </group>
          <group position={[454.542, 296.566, -207.504]} rotation={[0, -Math.PI / 2, 0]} scale={[6.622, 7.287, 7.287]}>
            <mesh geometry={nodes.DVN_74030_TTC_BK_Color_M09_0.geometry} material={materials.Color_M09} />
            <mesh geometry={nodes.DVN_74030_TTC_BK_Front_0.geometry} material={materials.Front} />
            <mesh geometry={nodes.DVN_74030_TTC_BK_LampFrame_0.geometry} material={materials.LampFrame} />
            <mesh geometry={nodes.DVN_74030_TTC_BK_Light_0.geometry} material={materials.Light} />
          </group>
          <group position={[145.943, 355.328, -300.43]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.GlassC_Black_0.geometry} material={materials.Black} />
            <mesh geometry={nodes.GlassC_Glass_0.geometry} material={materials.Glass} />
          </group>
          <group position={[-510.326, 232.719, -184.159]} rotation={[0, Math.PI / 2, 0]} scale={5.513}>
            <mesh geometry={nodes.HLB_840_Metal_0.geometry} material={materials.Metal} />
            <mesh geometry={nodes.HLB_840_Brushed_Metal1_0.geometry} material={materials.Brushed_Metal1} />
            <mesh geometry={nodes.HLB_840_Front001_0.geometry} material={materials['Front.001']} />
            <mesh geometry={nodes.HLB_840_FrontColor001_0.geometry} material={materials.Onyx} />
            <mesh geometry={nodes.HLB_840_Black_Metal_0.geometry} material={materials.Redhome_Model_Tree004_1} />
          </group>
          <group position={[-22.707, 125.682, -210.146]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Island_Closet_0.geometry} material={materials.Closet} />
            <mesh geometry={nodes.Island_Countertop_0.geometry} material={materials.Countertop} />
            <mesh geometry={nodes.Island_White_0.geometry} material={materials.White} />
          </group>
          <group position={[-451.518, 159.511, -184.857]} rotation={[0, Math.PI / 2, 0]} scale={[5.617, 5.43, 5.43]}>
            <mesh geometry={nodes.MS_622_BIS_Black_0.geometry} material={materials.Black} />
            <mesh geometry={nodes.MS_622_BIS_Front002_0.geometry} material={materials['Front.002']} />
            <mesh geometry={nodes.MS_622_BIS_FrontColor002_0.geometry} material={materials.Onyx} />
            <mesh geometry={nodes.MS_622_BIS_Brushed_Metal1001_0.geometry} material={materials['Brushed_Metal1.001']} />
            <mesh geometry={nodes.MS_622_BIS_Silver_0.geometry} material={materials.Redhome_Model_Tree004_3} />
          </group>
          <group position={[-252.936, 366.032, -538.916]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Oildecor_Redhome_Model_Tree004_3_0.geometry} material={materials.Redhome_Model_Tree004_3} />
            <mesh geometry={nodes.Oildecor_Material__2_0.geometry} material={materials.Material__2} />
            <mesh geometry={nodes.Oildecor_Material__2_0_1.geometry} material={materials.Material__2} />
            <mesh geometry={nodes.Oildecor_Redhome_Model_Tree004_1_0.geometry} material={materials.Redhome_Model_Tree004_1} />
            <mesh geometry={nodes.Oildecor_Glass_0.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Oildecor_Material__1_0.geometry} material={materials.Night_River_Black_Front} />
          </group>
          <group position={[34.018, 211.542, -232.294]} rotation={[-Math.PI / 2, 0, 0.865]} scale={22.23}>
            <mesh geometry={nodes.Oildecor002_Material_2_0.geometry} material={materials.Material_2} />
            <mesh geometry={nodes.Oildecor002_Material_3_0.geometry} material={materials.Material_3} />
            <mesh geometry={nodes.Oildecor002_Material_1_0.geometry} material={materials.Material_1} />
          </group>
          <group position={[434.894, 242.668, -66.776]} rotation={[-Math.PI / 2, 0, -1.745]} scale={35.889}>
            <mesh geometry={nodes.Oildecor003_Material_11_0.geometry} material={materials.Material_11} />
            <mesh geometry={nodes.Oildecor003_Material_4_0.geometry} material={materials.Material_4} />
            <mesh geometry={nodes.Oildecor003_Material_10_0.geometry} material={materials.Material_10} />
          </group>
          <group position={[-543.827, 28.663, -7.995]} rotation={[0, Math.PI / 2, 0]} scale={5.523}>
            <mesh geometry={nodes.RLF_74925_Logo_0.geometry} material={materials.Logo} />
            <mesh geometry={nodes.RLF_74925_Aluminum_0.geometry} material={materials.Aluminum} />
            <mesh geometry={nodes.RLF_74925__auto_23_0.geometry} material={materials.Redhome_Model_Tree004_1} />
            <mesh geometry={nodes.RLF_74925_Aluminium_Bright_0.geometry} material={materials.Aluminium_Bright} />
            <mesh geometry={nodes.RLF_74925_Black_0.geometry} material={materials.Black} />
            <mesh geometry={nodes.RLF_74925_Screen001_0.geometry} material={materials['Screen.001']} />
          </group>
          <group position={[-116.247, 271, -576.702]} rotation={[-Math.PI / 2, 0, 0]} scale={110.737}>
            <mesh geometry={nodes.Sink_Chrome_0.geometry} material={materials.Chrome} />
            <mesh geometry={nodes.Sink_Black_0.geometry} material={materials.Black} />
            <mesh geometry={nodes.Sink_Black_0_1.geometry} material={materials.Black} />
            <mesh geometry={nodes.Sink_Onyx_0.geometry} material={materials.Onyx} />
          </group>
          <group position={[156.856, 427.1, -382.133]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Spotlights_Light_0.geometry} material={materials.Light} />
            <mesh geometry={nodes.Spotlights_FrontColor003_0.geometry} material={materials.Onyx} />
            <mesh geometry={nodes.Spotlights_Glass_0.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Spotlights_White001_0.geometry} material={materials['White.001']} />
          </group>
          <group position={[193.686, 167.938, 246.847]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Stool_OakWood_0.geometry} material={materials.OakWood} />
            <mesh geometry={nodes.Stool_M_12_s21_0.geometry} material={materials.M_12_s21} />
          </group>
          <group position={[436.407, 183.623, -207.724]} rotation={[0, -Math.PI / 2, 0]} scale={[55.962, 51.999, 51.999]}>
            <mesh geometry={nodes.TRB_84300_TEKA_Black_0.geometry} material={materials.TEKA_Black} />
            <mesh geometry={nodes.TRB_84300_FrontColor_0.geometry} material={materials.Onyx} />
            <mesh geometry={nodes.TRB_84300_TRB_843_00_TCS_01_0.geometry} material={materials.TRB_843_00_TCS_01} />
          </group>
          <group position={[313.449, 304.262, 50.925]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 111.079, 119.91]}>
            <mesh geometry={nodes.Vent_Chrome_0.geometry} material={materials.Chrome} />
            <mesh geometry={nodes.Vent_Black_0.geometry} material={materials.Black} />
          </group>
          <group position={[-383.295, 129.609, -507.032]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 111.079, 100]}>
            <mesh geometry={nodes.Walls_ClosetGlossy_0.geometry} material={materials.ClosetGlossy} />
            <mesh geometry={nodes.Walls_Black_0.geometry} material={materials.Black} />
            <mesh geometry={nodes.Walls_White_0.geometry} material={materials.White} />
            <mesh geometry={nodes.Walls_Floor_0.geometry} material={materials.Floor} />
          </group>
          <group position={[377.995, 290.669, 103.338]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 111.079, 100]}>
            <mesh geometry={nodes['Wine+bottles_vinhos_pais_filhos_revisado_0'].geometry} material={materials.vinhos_pais_filhos_revisado} />
            <mesh geometry={nodes['Wine+bottles_wine_2_0'].geometry} material={materials.wine_2} />
            <mesh geometry={nodes['Wine+bottles_vino_Plan_B_Cabernet_Sauvignon_0'].geometry} material={materials.vino_Plan_B_Cabernet_Sauvignon} />
            <mesh geometry={nodes['Wine+bottles_artezin_bottle_0'].geometry} material={materials.artezin_bottle} />
          </group>
          <group position={[240.88, 308.421, -589.234]} rotation={[-Math.PI / 2, 0, 0]} scale={143.493}>
            <mesh geometry={nodes.biscuits_Black_0.geometry} material={materials.Black} />
            <mesh geometry={nodes.biscuits_Glass_0.geometry} material={materials.Glass} />
            <mesh geometry={nodes.biscuits_rama1_0.geometry} material={materials.rama1} />
            <mesh geometry={nodes.biscuits_rama1_0_1.geometry} material={materials.rama1} />
            <mesh geometry={nodes.biscuits_Translucent_Glass_Blue_0.geometry} material={materials.Translucent_Glass_Blue} />
            <mesh geometry={nodes.biscuits_M_0004_HotPink_0.geometry} material={materials.M_0004_HotPink} />
            <mesh geometry={nodes.biscuits_cookies_0.geometry} material={materials.cookies} />
            <mesh geometry={nodes.biscuits__2_0.geometry} material={materials.material} />
            <mesh geometry={nodes.biscuits__1_0.geometry} material={materials.material_70} />
            <mesh geometry={nodes.biscuits_Color_000_0.geometry} material={materials.Onyx} />
            <mesh geometry={nodes.biscuits_Color_B25_0.geometry} material={materials.Color_B25} />
          </group>
          <group position={[210.188, 248.841, -600.095]} rotation={[-Math.PI / 2, 0, 0]} scale={153.575}>
            <mesh geometry={nodes.utilitys001_Aluminium_0.geometry} material={materials.Aluminium} />
            <mesh geometry={nodes.utilitys001_Chrome_0.geometry} material={materials.Chrome} />
            <mesh geometry={nodes.utilitys001_Chrome_0_1.geometry} material={materials.Chrome} />
            <mesh geometry={nodes.utilitys001_M_96_96_96_0.geometry} material={materials.M_96_96_96} />
            <mesh geometry={nodes.utilitys001_Glass_0.geometry} material={materials.Glass} />
            <mesh geometry={nodes.utilitys001_white_dirt_0.geometry} material={materials.white_dirt} />
            <mesh geometry={nodes.utilitys001__Charcoal__0.geometry} material={materials.Charcoal} />
            <mesh geometry={nodes.utilitys001_Color_B24_0.geometry} material={materials.Color_B24} />
            <mesh geometry={nodes.utilitys001_Wood_Plywood_Knots_0.geometry} material={materials.Wood_Plywood_Knots} />
            <mesh geometry={nodes.utilitys001_Asphalt_New_0.geometry} material={materials.Asphalt_New} />
            <mesh geometry={nodes.utilitys001_Color_C19_0.geometry} material={materials.Color_C19} />
          </group>
          <group position={[437.881, 211.863, -407.375]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={116.819}>
            <mesh geometry={nodes.utilitys002_Glass_0.geometry} material={materials.Glass} />
            <mesh geometry={nodes.utilitys002_Glass_0_1.geometry} material={materials.Glass} />
            <mesh geometry={nodes.utilitys002_Sugartext_0.geometry} material={materials.Sugartext} />
            <mesh geometry={nodes.utilitys002_coffee_beans_0.geometry} material={materials.coffee_beans} />
            <mesh geometry={nodes.utilitys002_Oats_0.geometry} material={materials.Oats} />
            <mesh geometry={nodes.utilitys002_Flour_0.geometry} material={materials.Flour} />
            <mesh geometry={nodes.utilitys002_M_1306576471823_0.geometry} material={materials.M_1306576471823} />
            <mesh geometry={nodes.utilitys002_seamless_oats_texture_by_hhh316_d30r0ml_0.geometry} material={materials.seamless_oats_texture_by_hhh316_d30r0ml} />
            <mesh geometry={nodes.utilitys002_Sugar_0.geometry} material={materials.Sugar} />
          </group>
          <group position={[65.17, 216.979, -591.527]} rotation={[-Math.PI / 2, 0, 0]} scale={108.718}>
            <mesh geometry={nodes.utilitys003_M_10ravens_copper_013_003b1_0.geometry} material={materials.M_10ravens_copper_013_003b1} />
            <mesh geometry={nodes.utilitys003_M_10ravens_metal_013_003d1_0.geometry} material={materials.M_10ravens_metal_013_003d1} />
            <mesh geometry={nodes.utilitys003_M_10ravens_plastic_013_008d1_0.geometry} material={materials.M_10ravens_plastic_013_008d1} />
            <mesh geometry={nodes.utilitys003_Chrome_0.geometry} material={materials.Chrome} />
          </group>
          <group position={[-143.913, 372.407, -542.781]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.utilitys005_M_10ravens_ceramic_013_015c1_0.geometry} material={materials.M_10ravens_ceramic_013_015c1} />
            <mesh geometry={nodes.utilitys005_M_10ravens_ceramic_013_015c1_0_1.geometry} material={materials.M_10ravens_ceramic_013_015c1} />
            <mesh geometry={nodes.utilitys005_M_10ravens_gold1_0.geometry} material={materials.M_10ravens_gold1} />
          </group>
          <group position={[409.761, 329.175, -69.35]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={150.06}>
            <mesh geometry={nodes.utilitys006_M_0018_Brown_0.geometry} material={materials.M_0018_Brown} />
            <mesh geometry={nodes.utilitys006__22_0.geometry} material={materials.material_93} />
            <mesh geometry={nodes.utilitys006_clear_glass_Archetectural_0.geometry} material={materials.clear_glass_Archetectural} />
            <mesh geometry={nodes.utilitys006_chrome_0.geometry} material={materials.Redhome_Model_Tree004_1} />
            <mesh geometry={nodes.utilitys006_electrolux_black_plastic_glossy_0.geometry} material={materials.electrolux_black_plastic_glossy} />
            <mesh geometry={nodes.utilitys006_kkk_0.geometry} material={materials.material_96} />
            <mesh geometry={nodes.utilitys006_kabinet_0.geometry} material={materials.Onyx} />
          </group>
          <mesh geometry={nodes.DDDD005_Glass_0.geometry} material={materials.Glass} position={[412.596, 378.504, -371.211]} rotation={[-Math.PI / 2, 0, 0]} scale={55.029} />
          <mesh geometry={nodes.DDDD006_M_0c9925396044fa2f8bfaada00e4576b8_0.geometry} material={materials.M_0c9925396044fa2f8bfaada00e4576b8} position={[406.653, 313.413, -324.644]} rotation={[-Math.PI / 2, 0, -0.723]} scale={87.829} />
          <mesh geometry={nodes.Oildecor001_FrontColor004_0.geometry} material={materials.Onyx} position={[-249.474, 327.006, -548.001]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Skirting_Board_Onyx_0.geometry} material={materials.Onyx} position={[455.417, 40.656, 246.2]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Sphere__0.geometry} material={materials.Sphere__0} position={[385.361, 340.476, 99.471]} rotation={[-Math.PI / 2, 0, 0]} scale={[25.32, 27.45, 20.722]} />
          <mesh geometry={nodes.Sphere001__0.geometry} material={materials.Sphere__0} position={[405.883, 380.067, -67.86]} rotation={[-Math.PI / 2, 0, 0]} scale={[24.528, 26.591, 20.075]} />
          <mesh geometry={nodes.WoodCabinet_OakWood_0.geometry} material={materials.OakWood} position={[162.494, 237.549, -245.921]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.ff001_OakWood_0.geometry} material={materials.OakWood} position={[26.545, 186.074, -532.644]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[105.171, 105.171, 63.659]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/modern_kitchen.glb')
